//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_CommerceDBEntities : DbContext
    {
        public E_CommerceDBEntities()
            : base("name=E_CommerceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblColor> tblColor { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblRoles> tblRoles { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
        public virtual DbSet<tblSubCategory> tblSubCategory { get; set; }
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblAdminRegister> tblAdminRegister { get; set; }
        public virtual DbSet<tblCart> tblCart { get; set; }
        public virtual DbSet<tblUserRegister> tblUserRegister { get; set; }
        public virtual DbSet<tblWishlist> tblWishlist { get; set; }
        public virtual DbSet<tblUserLogin> tblUserLogin { get; set; }
    }
}
