//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblColor
    {
        public int ColorID { get; set; }
        public string ColorName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Image { get; set; }
    }
}
