//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public int CartID { get; set; }
        public Nullable<int> UserRegisterID { get; set; }
        public string ProductName { get; set; }
        public string UnitPrice { get; set; }
        public string Image { get; set; }
        public string Quantity { get; set; }
    }
}
